### PR TITLE
Angie syrphidae

### PR DESCRIPTION
**Pull request by aammd**

### CODE REVIEW

**Comment by dsrivast** [comment]
hi @aammd , I can see in their notes that @angienic and saulo have changed lines for both the syrphidae and ceratopogonidae in their "syrphidae" pull request, but the daff file is just for syrphids. Would you be able to generate a daff for the ceratopogonids too?

**Comment by aammd** [comment]
hello @dsrivast ! on it

**Comment by aammd** [comment]
@dsrivast Syrphid daff should now be up-to-date

**Comment by dsrivast** [comment]
Hi @angienic and Saulo: nice job on this. I have to apologize for the awful state of the Syrphids, it looks like they never were properly researched and documented in the Traits_All_Sources.doc. I took the research that you did and merged it with two papers by Rotheray that explicitly looked at aquatic syrphids, plus Tachet's traits, and came up with a generic Syrphid trait matrix (the FD and FG traits depend on genus, the others not). I will email this to you.

to do list:
1. Update all syrphids using the new trait matrix....sorry.
2. Please revert the traits in K145 (Pupa Atrichopogon). This should have Atrichopogon traits. Please also change to subfamily=Forcipomyiinae, genus=Atrichopogon, Taxonomic.resolution=G
3. Please change all traits in K172 and K178 to match those of Forcipomyiinae. These two species are in the obscure and ancient subfamily Leptoconopinae which is ecologically like Forcipomyiinae. Please also change the subfamily name of K172 to Leptoconopinae.
4. Please give K140, K142, (both Sphaeromias sp)  K131 (Stilobezzia) the same traits as Bezzia, as these genera are poorly known but are predators like Bezzia. 
5. Please give K131 (Ceratopogoninae) the modal traits for the Ceratopogoninae subfamily.

**Pull request merged**
