### PR TITLE
Melissa oligochaete

### PR DESCRIPTION
**Pull request by lmguzman**
Alrighty, I think im done :)

### CODE REVIEW

**Comment by dsrivast** [comment]
@lmguzman All's good here, except the following changes should be made:

K643, k644, k645, k646, k647: BS3 ->0, BS4->3, BS5->2  this is because BS is the maximum body size, not the distribution of body sizes. These are all essentially the same species, so I agree they must be consistent.

K639 : LO3 2->0, LO4 0->2, LO5 0-> 3
K640: LO3 0->1, LO4 2->3 
The K639, K640 changes are because these species are Lumbricina and Tubificina, two types of oligochaetes (unlike Naididae) that do really burrow for a living, also brings K640 in line with other Tubificina.

Either you can do these changes if you're online, or I will make sure they get done.

**Comment by lmguzman** [comment]
I can change them and commit again

**Comment by lmguzman** [comment]
@dsrivast  I can't find 639 and 640 on the oligochaete tsv file.

**Comment by dsrivast** [comment]
@adletaw I notice that the traits for two oligochaete species K639 and K640 need some trait updates, but they are not on the oligochaete tsv file that @lmguzman is working on. Is there a fast way to figure out which snipped out file these species ended up on?

**Comment by lmguzman** [comment]
@aammd you guys eliminated repeated entries before splitting the tsv files right? @dsrivast  could those entries be those repeated ones?

**Comment by aammd** [comment]
@lmguzman @dsrivast @adletaw I found them! the are in `tachet_00_unaffected.tsv`. In [these lines](https://github.com/SrivastavaLab/bwg_names/blob/34a7aa4973075b0428f224c1c4c723dcc4b6a53c/Rscripts/13_splitting_tachet_traits.R#L80-L108) it seems that @adletaw pulled out the unaffected groups by family ; these oligochaetes are unique in their families.

@lmguzman , may I suggest you edit that file as well on this same branch, then push it to here. Then that modified file will also be added to this PR

**Comment by lmguzman** [comment]
Alrighty, I changed directly the tachet_00_unaffected.tsv

**Comment by aammd** [comment]
@lmguzman good work!
@dsrivast the daffs are now updated to show Melissa's latest work!

**Comment by dsrivast** [comment]
Sorry @lmguzman Melissa, noticed two other inconsistencies before we merge:
1. K646 LO7: NA->0
2. The species identified only to suborder Muscomorpha are sometimes given traits and sometimes not. Could you copy the traits from K578 and paste on K579, K595, K105-K109, K438-K440.
Once those are done, we're ready to go!

**Comment by adletaw** [comment]
Weird!  I will take a look...

**Comment by adletaw** [comment]
Thanks for finding that @aammd

On 2015-08-31 02:41 PM, Andrew MacDonald wrote:
>
> @lmguzman <https://github.com/lmguzman> @dsrivast 
> <https://github.com/dsrivast> @adletaw <https://github.com/adletaw> I 
> found them! the are in |tachet_00_unaffected.tsv|. In these lines 
> <https://github.com/SrivastavaLab/bwg_names/blob/34a7aa4973075b0428f224c1c4c723dcc4b6a53c/Rscripts/13_splitting_tachet_traits.R#L80-L108> 
> it seems that @adletaw <https://github.com/adletaw> pulled out the 
> unaffected groups by family ; these oligochaetes are unique in their 
> families.
>
> @lmguzman <https://github.com/lmguzman> , may I suggest you edit that 
> file as well on this same branch, then push it to here. Then that 
> modified file will also be added to this PR
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SrivastavaLab/bwg_names/pull/49#issuecomment-136509447>.
>

-- 
Alathea D. L.
PhD Candidate, Srivastava Lab
www.zoology.ubc.ca/~srivast

**Pull request merged**
